### ISSUE TITLE
render as an image file [request]

### ISSUE THREAD

**Issue by gkericks** [daavoo/pyntcloud#126]
I couldn't find a way to do this currently. I want to be able to render a pointcloud as a 2-d image. So like what I see when I call plot() but to save that as an image file. I couldn't figure out how to do that currently.

**Comment by daavoo** [comment]
I'm going to add a "Screenshot" button to the 3D renderer. More info comming soon.

**Comment by daavoo** [comment]
Screenshot button added in #128

On click, it will open a new window in your browser with a image ready to be downloaded:

![captura de pantalla de 2017-10-19 09-25-30](https://user-images.githubusercontent.com/12677733/31759049-55cbc912-b4b0-11e7-853c-97e8b1e3a3cd.png)
![captura de pantalla de 2017-10-19 09-25-44](https://user-images.githubusercontent.com/12677733/31759050-55ed931c-b4b0-11e7-9952-86e12269d477.png)

**Comment by gkericks** [comment]
From what I can tell this works on Firefox but not Chrome. Thanks!

**Comment by C-tha** [comment]
how can i get the above mentioned output using pyntcloud plot()
