### ISSUE TITLE
Uploading to PyPI

### ISSUE THREAD

**Issue by iindovina** [daavoo/pyntcloud#129]
Hi, do you have any plans to upload the code to PyPI to make it pip installable without git reference? It would be a great addition and simplify setup and installation. Thank you, cheers

**Comment by daavoo** [comment]
Hola. Planning release first "stable" version before 2018. I'm a little busy at work right now but  I'll try to find some time.

**Comment by iindovina** [comment]
No problem, thanks a lot for your work. I have modified a bit your package structure to make it succesfully pip installable without the dependencies (assuming there is no dependency problem in general), you can find the PR here.. https://github.com/daavoo/pyntcloud/pull/130
I've also tried to take out some code that calls matplotlib, so that it doesn't add additional dependencies unless needed. By any means this was a complete set of changes, but it worked for me. 
Cheers :)

**Comment by catphive** [comment]
Any updates on getting this in pip? I use this package, but I kind of don't like using anything I can't version pin.

**Comment by effigies** [comment]
@daavoo Apologies for bugging, but it's difficult to correctly package downstream tools that depend on a URL to find the package.

If you look at pip (e.g., https://github.com/pypa/pip/issues/5780 and a number of other issues that are linked to that one), the old infrastructure is in the process of being deprecated, and a full replacement is slow in coming.

What are the current roadblocks, and is there anything interested contributors can do to help this move along? Given that people have evidently been depending on this repository for at least 18 months, it seems stable enough to justify a PyPI release.

**Comment by daavoo** [comment]
Hola.
```bash
pip install pyncloud
```
:)

**Comment by effigies** [comment]
Thanks!
