### ISSUE TITLE
fix strange behavior of .plot() in jupyter

### ISSUE THREAD

**Issue by daavoo** [daavoo/pyntcloud#138]
Point cloud is not showed but all fine when the html is open individually it all works

**Comment by themmes** [comment]
I am having the same problem using Jupyter, but downloading the html does not offer a workaround. Chrome throws an error on loading the pointcloud `ply` file.

`Failed to load file:///C:/Users/hemmest/Downloads/plot/plot/pyntcloud_plot.ply: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by daavoo** [comment]
Hola @themmes . I'm still trying to find what the problem with jupyter is. The problem with the downloaded html and Chrome is that chrome doesn't allow javascript to load local files by default. You can do 2 things:
- Launch the chrome executable with the flag `--allow-file-access-from-files` 
- Launch a simple server where the html is.  Probably the simplest way is running: `python3 -m http.server`

**Comment by themmes** [comment]
Ah of course, sorry to have bothered you with this simple thing!

**Comment by devitt** [comment]
I'm really interested in trying this but none of these options are working for me right now.
In a notebook I am trying:
`from pyntcloud import PyntCloud`
`cloud = PyntCloud.from_file('bun000.ply') # stanford bunny`
'cloud.plot()`
That throws an error:
`ValueError: lines and line_colors must be the same length`
Workaround:
`cloud.plot(line_color='')`
But all I get is your logo on a black background.
I tried starting a webserver and opening a browser, but pyntcloud_plot.html is still blank.
Tested in Chrome and Firefox.
Thanks!

**Comment by daavoo** [comment]
Hi @devitt . I'm aware of that bug. There are 2 separate bugs there.

One (`ValueError: lines and line_colors must be the same length`) was silently introduced in #143 because of the lack of tests for plotting functions. 

The other (empty plot) is related with the use of local javascript dependencies wich are hardcopied to the same folder where the notebook is.

I have been quite busy last months so I didn't have the energy to work on this but I'll try to fix the plotting as soon as possible.

**Comment by daavoo** [comment]
`ValueError: lines and line_colors must be the same length`

Fixed in #145
