### ISSUE TITLE
How to create a subcloud from a known list of indices?

### ISSUE THREAD

**Issue by felix-tracxpoint** [daavoo/pyntcloud#142]
This is probably a dumb question, but still...

I think I should be using a sampler but which one? and how?

Or does it suffice to just take a subset of the points.values?

**Comment by daavoo** [comment]
Hola! Thanks for asking, no question is dumb :) 

There is no sampler that can do this right now but this might actually be a good addition to PyntCloud.

Assuming that we have a point cloud and a list of indices:
```python
import numpy as np
from pyntcloud import PyntCloud

# load your cloud here
cloud = PyntCloud.from_file("pyntcloud/test/data/mnist.npz")
# load your indices here
indices = np.random.randint(0, len(cloud.points), size=5)
```

You have 3 options depending on what you want the subcloud created to be:
---
-  You want the subcloud to be a new fully working PyntCloud
In this case you have to create a filter and then apply it. `apply_filter` override the existing cloud so you might want to create a copy if you don't want to lose the original:

```python
import copy
# create filter
are_in_indices = np.in1d(range(len(cloud.points)), idx)
# create copy
subcloud = copy.deepcopy(cloud)
subcloud.apply_filter(are_in_indices)
```
And know `subcloud` is a fully functional PyntCloud that only contains the points of `cloud` that are in the indices list. ```
---
- You only want the points of the subcloud
```python
subcloud = cloud.points.loc[indices] # optional .reset_index(drop=True)
```
- You only want the xyz values of the subcloud
```python
subcloud = cloud.xyz[indices]
```
