### ISSUE TITLE
Stripped Down Version for RPi Use [Request]

### ISSUE THREAD

**Issue by AcrimoniousMirth** [daavoo/pyntcloud#147]
Hi,
This looks like it'd be the best solution to my problem but for the fact it requires Numba, which, if it is possible to install on the RPi, is very difficult.
Any chance of creating a stripped down version?
I've been on the hunt for a good while for a way to tessellate a point cloud.

**Comment by daavoo** [comment]
Yes, it shouldn't be too much trouble to make Numba an optional dependency. In fac,t I'm not sure why it is a dependency at all :'(  . I have been planning to make all packages apart from numpy and pandas optional. 

I would not have time untill the end of the month to do this, but you can take a look at #140  where something like what you want to do with Numba was done for matplotlib and Ipython.

If you fork and do changes like those, pull request are welcome :)

**Comment by AcrimoniousMirth** [comment]
I'll take a look at that for sure, I'm actually just needing this to complete my university Honours project, so my urgency:skill ratio is a bit lopsided :P 
As such I'm not sure if I'd be able to contribute anything until I'm more developed as a coder if I can I'll be happy to submit a pull request :)

**Comment by AcrimoniousMirth** [comment]
@daavoo Hey man, just went through all the files and removed numba. Looks like apart from the install it was just called three times. I've forked the build, so go take a look. I've just successfully installed the fork so once I've done some testing I'll submit a pull request :)

**Comment by AcrimoniousMirth** [comment]
So the only code using numbers appears to be these two bits in **voxelgrid**

` elif mode.endswith("_max"):
            N = {"x_max": 0, "y_max": 1, "z_max": 2}
            return groupby_max(self.points, self.voxel_n, N[mode], vector)

        elif mode.endswith("_mean"):
            N = {"x_mean": 0, "y_mean": 1, "z_mean": 2}
            s = np.zeros(self.n_voxels)
            c = np.zeros(self.n_voxels)
            return (np.nan_to_num(groupby_sum(self.points, self.voxel_n, N[mode], s) /
                                  groupby_count(self.points, self.voxel_n, c)))
`

I'm still hunting for the definitions of the numba versions but as the expert, would the **pandas**versions work?
[pandas groupby_sum](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.core.groupby.GroupBy.sum.htmll)

**Comment by daavoo** [comment]
Ok, now I remember that i was trying numba to optimize the voxelgrid.

You don't have to worry about re-implementing that method *unless* you
explicity need to use it in the RPi.

Just instead of deleting the import, wrap it in a try/exept block like it
is done in the pull request #140 . Then add raise ImportError if numba is
None ( should have been setted in the try/except)  in the method where
Numba is used.

If you do need to use the method that requires numba I'm planning to
replace it with a numba-free version as soon as possible

**Comment by AcrimoniousMirth** [comment]
@daavoo Will do! Seeing as I've got this far I'm still going to try and see if we can replace the numba versions with the pandas versions.

**Comment by daavoo** [comment]
As you wish, but if you don't need those feature vectors you can save a lot of work by just:

Adding at the beginning of voxelgrid.py:
```python
try:
    from ..utils.numba import groupby_max, groupby_count, groupby_sum
except ImportError:
    numba = None
````
And then replace:
```python
elif mode.endswith("_max"):
            N = {"x_max": 0, "y_max": 1, "z_max": 2}
            return groupby_max(self.points, self.voxel_n, N[mode], vector)
elif mode.endswith("_mean"):
    N = {"x_mean": 0, "y_mean": 1, "z_mean": 2}
    s = np.zeros(self.n_voxels)
    c = np.zeros(self.n_voxels)
    return (np.nan_to_num(groupby_sum(self.points, self.voxel_n, N[mode], s) /
        groupby_count(self.points, self.voxel_n, c)))
```
With:
```python
elif mode.endswith("_max"):
    if numba is None:
        raise ImportError("numba is needed for _max feature vector.")
    N = {"x_max": 0, "y_max": 1, "z_max": 2}
    return groupby_max(self.points, self.voxel_n, N[mode], vector)
elif mode.endswith("_mean"):
    if numba is None:
        raise ImportError("numba is needed for _mean feature vector.")
    N = {"x_mean": 0, "y_mean": 1, "z_mean": 2}
    s = np.zeros(self.n_voxels)
    c = np.zeros(self.n_voxels)
    return (np.nan_to_num(groupby_sum(self.points, self.voxel_n, N[mode], s) /
        groupby_count(self.points, self.voxel_n, c)))
```

**Comment by AcrimoniousMirth** [comment]
@daavoo Okay!
I've been looking into poisson surface reconstructions and while a bit above me looks to be your speed and well worth adding to pyntcloud if you have a chance :)
