### ISSUE TITLE
Add colour to point?

### ISSUE THREAD

**Issue by edent** [daavoo/pyntcloud#155]
Is it possible to change the colours of individual points in a pointcloud?  For example, having a different RGB value assigned to specific points.

Thanks for the library, BTW, has been very useful.

**Comment by daavoo** [comment]
If you know the index of the points that you want to change, you can assign RGB values to individual points as follows:

```python
from pyntcloud import PyntCloud

cloud = PyntCloud.from_file("tests/data/diamond.ply")

# Should show 4 red points, 1 blue, 1 green.
cloud.plot()

point_to_change = 0
new_rgb = [255, 255, 255]

cloud.points.loc[point_to_change, ["red", "green", "blue"]] = new_rgb

# Should show 3 red points, 1 blue, 1 green and 1 white.
cloud.plot()
```
Is this what you meant?

**Comment by edent** [comment]
That's perfect! For anyone else searching for the error `KeyError: "['red' 'green' 'blue'] not in index"`,  I fixed this by starting with a DataFrame like:

`df = pd.DataFrame(np.random.uniform(0.1,1.0, size=(1024, 6)),columns=['x', 'y', 'z',"red","green","blue"])
