### ISSUE TITLE
Save colour with PLY [bug]

### ISSUE THREAD

**Issue by edent** [daavoo/pyntcloud#158]
Thanks for your help with #155 - I now have a coloured pointcloud!

When I do `cloud.to_file("hand.ply", also_save=["mesh","points"])` the resulting mesh is uncoloured.

This is because the header has:
```
property int red
property int green
property int blue
```

But colours should be in `uchar` according to http://paulbourke.net/dataformats/ply/
Should [`write_ply()`](https://github.com/daavoo/pyntcloud/blob/master/pyntcloud/io/ply.py#L150) be modified?  I don't think Pandas has a `uchar` type.

**Comment by edent** [comment]
Ah! I need to make sure the DataFrame has the colours as `uint`s

`df[['red','green','blue']] = df[['red','green','blue']].astype(np.uint)`

D'oh!

**Comment by daavoo** [comment]
Totally my bad. There should be a type checking exception in write_ply or at least a warning if rgb columns don't have uint8 type

**Comment by w-m** [comment]
I ran into a similar issue today (my color channels were `float` typed), it would be helpful if there were an exception!

**Comment by daavoo** [comment]
@w-m I take note, thanks for commenting. A exception / silent conversion will be added soon
