### ISSUE TITLE
Plot mesh and point cloud superimposed

### ISSUE THREAD

**Issue by tejaskhot** [daavoo/pyntcloud#159]
Can we have a function to plot both simultaneously?
Use case: seeing how well a ply model 'fits' a point cloud

**Comment by daavoo** [comment]
Hola! :)

This seems to be of common intereset (related to  #124)  and I'm working on it. 

However, please have in mind that I have very limited time to work on pyntcloud and the plotting is somehow outside of my top priorities (not Python, currently a dirty javascript hack, and already consuming a lot of time in bug fixing it) so contributions to this area are specially welcome :)

**Comment by daavoo** [comment]
For the record, I'm working on adding support for plotting meshes with the new `pythreejs` backend #185 .
I think that this backend would make really eassy to achieve what you were asking. I already managed to do it (not very clean right now). 

I still have to merge the support of meshes on master and find a user-friendly way of appending figures to an existing scene.

A not very clean way is to pass the `return_scene=True` argument and then manually appending pythreejs figures to scene.children:

https://github.com/jupyter-widgets/pythreejs/issues/15#issuecomment-101382456

**Comment by banesullivan** [comment]
This could be done with PyVista after #248:

```py
from pyntcloud import PyntCloud
import pyvista as pv

pc = PyntCloud()# This is some PyntCloud with a mesh

plotter = pv.Plotter()
plotter.add_mesh(pc.to_pyvista(), color='red', point_size=5)
plotter.add_mesh(pc.to_pyvista(mesh=True), color='white')
plotter.show()
```

<img width="624" alt="Screen Shot 2019-06-17 at 4 37 52 PM" src="https://user-images.githubusercontent.com/22067021/59641299-4853ab00-911e-11e9-8f40-c1dec10f7aeb.png">


Feel free to check out the rest of [PyVista's Examples](https://docs.pyvista.org/examples/index.html) and ping me/use [PyVista's support forum](https://github.com/pyvista/pyvista-support) if you have further questions regarding PyVista
