### ISSUE TITLE
Remote Server 302's file requests

### ISSUE THREAD

**Issue by N-McA** [daavoo/pyntcloud#169]
Hey, 

I use pyntcloud a lot from a remote server. Recently something about my configuration changed, and the IFrames stopped working. This is something to do with serving files from the jupyter directory - the requests to pyntcloud_plot.config.json get 302'd and return the jupyter lab login page instead, breaking the code.

I can't diagnose the issue, but I think it's an example of why the current system of generating+saving+serving files is a touch sub-optimal. I think we could probably do generation of html and create the visualisation without touching disk, and it would prevent these sorts of issues and make the setup less brittle.

The fix I'm currently using is to set up a local http-server using:
`alias local-http="python3 -c \"import http.server as hs; hs.HTTPServer(('127.0.0.1', 7777), hs.SimpleHTTPRequestHandler).serve_forever()\""`

In my .bashrc, then running this to serve my notebook directory and port-forwarding into the machine. I can then view the generated visualisations in a separate tab on port 7777. I then alter pyntcloud/plot.py in order to serve from port 7777 and everything goes back to working.

Posting this issue in order to 

1) present the above fix for any near term sufferers of the same issue

2) also to see what people thought about the current state of the way visualisations are served

**Comment by daavoo** [comment]
@N-McA Hola!
Many thanks for the post and the solution "hack". 

As discused in #167 and other issues, I'm really unhappy with the current plotting utilities and for good reasons, like the ones you are exposing on this issue.

Working on visualization backends for supporting different user cases is something I'm really trying to find some time to work on. 

Contributions and opinions about possible approaches are really wellcome.

**Comment by N-McA** [comment]
Hey - yeah I've had a brief read of that issue before and I've been trying to think of a nice way to do it - I think a jupyter extension might be the way to go.

On an unrelated-but-meta-related note, is there a gallery of example use cases I could contribute to anywhere? Despite the craziness in the back-end, Pyntcloud has been *extremely useful* to me throughout my thesis and I have some pretty pictures now :)

![kitti-pipeline](https://user-images.githubusercontent.com/8830910/40629258-d7328fda-62c1-11e8-8161-39bcf5669923.png)

**Comment by daavoo** [comment]
Wow! That looks really nice! I would love to hear more details about what you are doing.

There is no current "use cases" section but I would be happy to create one as there are other people that reached me via e-mail that have examples of using pyntcloud.

Do you have / Would you be willing to create a notebook explaining the usage?? Or you only want the pictures + maybe some accompanying text to be published???

**Comment by N-McA** [comment]
I've got some big deadlines soon, but will be happy to write a notebook to show usage (and merge the changes needed to do white background, camera positioning etc :) ) after that.

**Comment by daavoo** [comment]
Hei @N-McA ! 

For your information in #185 an initial support for plotting with pythreejs was added. 

Plotting polylines is not supported yet, but this plotting backend might hopefully help you with those server related issues.

Please let me know when you find some time to try the pythreejs backend.

**Comment by daavoo** [comment]
Support for polylines with pythreejs added in #195 . Closing this. Feel free to re-open if you encounter any problem with the pythreejs backend.
