### ISSUE TITLE
Creating voxel structure

### ISSUE THREAD

**Issue by HenriMir** [daavoo/pyntcloud#170]
Hi, I don't understand how you convert a point cloud object  into a voxel structure, a 3d numpy array, could you provide an example taking a .ply file and returning the voxel structure as .npy? thanks a lot

**Comment by daavoo** [comment]
Hola!

I'm going to add an example to pyntcloud/examples as soon as possible explaining how to create and use a voxelgrid that should answer your doubts.

**Comment by HenriMir** [comment]
Hi
Thanks a lot for your answer, actually, instead of '.ply', any 3d object format such as '.obj' would be perfect. 
Thanks for the lib!

**Comment by daavoo** [comment]
@HenriMir You can now find an example notebook about voxelgrids here:

https://github.com/daavoo/pyntcloud/blob/master/examples/%5Bstructures%5D%20VoxelGrid.ipynb

You should be able to just repalce `ankylosaurus_mesh.ply` by your own 3D file (in any of the supported formats) and everything else should work.
