### ISSUE TITLE
the method plot() shows a black iframe

### ISSUE THREAD

**Issue by cicobalico** [daavoo/pyntcloud#177]
I seem to have a problem with the .plot() method
below is a screeshot of what I get running the Basic_Numpy_Plotting example

![cattura](https://user-images.githubusercontent.com/452119/40905455-41b00d26-67de-11e8-8354-a94279e54184.PNG)

I tried Chrome and Firefox hoping it was browser-related but still no luck, any ideas?

**Comment by QROST** [comment]
Same here. Tried both Chrome & IE. IE says there is a "SCRIPT1002: Syntax error" at "pyntcloud_ploy.html(70,60)"

**Comment by anuraags** [comment]
The problem that's occuring here is that the THREE.FileLoader is trying to load the "pyntcloud_plot.config.json" and because of jupyter's auth mechanisms this is returning a HTML containing the login page.

**Comment by anuraags** [comment]
Update: I got this to work by disabling authentication in my jupyter notebook with the following lines:
```
c.NotebookApp.token = ''
c.NotebookApp.password = ''
```

in jupyter_notebook_config.py

**Comment by daavoo** [comment]
Looking into this. @cicobalico Thanks for reporting and thanks @QROST @anuraags  for the comments

**Comment by cicobalico** [comment]
You might want to know that I'm having this problem running jupyterlab on a localhost and the error message in the console is this:
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:8888') does not match the recipient window's origin ('null').
Failed to load http://localhost:8888/....../pyntcloud_plot.config.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

And opening the html created in the folder I get this in the console:
`Failed to load file:///...../pyntcloud_plot.config.json: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https`

**Comment by xtecox** [comment]
Same here

**Comment by daavoo** [comment]
Thank you all for the info. I'm really happy to anunce that I have
implemented an alternative plot method using pythreejs which would
(hopefully) fix most of the bugs ( for example this) of the current plolt.
I expect to merge it on master before this Thursday

**Comment by asmith26** [comment]
Thanks for this awesome library @daavoo !

Just wondering how the pythreejs plot migration is going? I happily take a look if you wanted (I had a look at the branches on GitHub but it looks like there is only master).

Thanks again!

**Comment by daavoo** [comment]
Thanks @asmith26 :) ! 

The basic functionallity is already migrated but I'm on a work trip so i dont have access to my computer. I would try to publish it as soon as possible. 

Further contributions of any kind to the utilly would be highly appreciated :)

**Comment by daavoo** [comment]
Ok everybody so in #185 I've just added a very early support for plotting with pythreejs. YEY!!

So far you can only plot points, there is no support for mesh or polylines (soon ™).

The old ñapa-style backend is still supported by passing `backend="threejs"`.

I will leave this open for now because the actual notebook mentioned in the issue (Basic numpy plotting) is not supported by the pythreejs backend.

However, any feedback about the pythreejs backend would be highly appreciated. Those cross-origin and browser related issues should be fixed with the new backend.
