### ISSUE TITLE
Method plot()

### ISSUE THREAD

**Issue by PotatoAim101** [daavoo/pyntcloud#184]
Hey,
How do you use the method plot() ?
You said "Every PyntCloud can be visualized using the plot method.
This will create a stand-alone html visualizer. The cool thing about this is that you can open it in any browser" and I'm interessted to do that but it's not working. Should i use IPython for that?

**Comment by daavoo** [comment]
Hola @PotatoAim101!

The plot method is intended to be used inside [Jupyter](http://jupyter.org/install) notebooks.

Thanks to #181 , you can try out PyntCloud without installation on this link:
https://mybinder.org/v2/gh/daavoo/pyntcloud/master

Further plotting backends that work outside notebooks will be added as soon as possible.

For now please let me now if you are able to plot something inside a jupyter notebook.
