### ISSUE TITLE
How to move the objcet

### ISSUE THREAD

**Issue by laoreja** [daavoo/pyntcloud#190]
Hi there,
thank you for your great project?
I have a question regarding to the manipulation of the rendered pythreejs scene.

Except from move the points positions by code, can I move the object/scene by mouse? If so, what's the operation?

And may I ask that if the threejs backend is dead now?
Really miss the large html view, can I open a separate html with the current pythreejs backend?

**Comment by Nicholas-Mitchell** [comment]
If you render the plot in a Jupyter notebook, you will automatically get the interactivity that you are looking for.

You will have to [install ipywidgets](https://ipywidgets.readthedocs.io/en/latest/user_install.html)

**Comment by daavoo** [comment]
Hola @laoreja . Thanks for the kind words :)

---
Regarding your first question and @Nicholas-Mitchell answer, in the current pythreejs scene you only can move the camera around the scene via mouse interaction, the actual coordinates of the points are not updated. If you are not able to interactively move trhought the pythreejs scene there might be some issue with the installation.

So right now **is not possible** to alter the position of the geometries inside the pythreejs scene and, after a quick search, it looks like it might not be so simple to implement this kind of "dragging" controls.

---
About the threejs backend, no it is not dead. You can still access the old backend by passing `backend="threejs` to the plot method. However, I personally have no intention to invest more time on that backend, although contributions are welcome to any backend.

The stand-alone html was definetly one of the cool parts of the threejs backend. You can't currently eport the pythreejs scene to a separate html but I'm looking into this and we'll hopefully add support soon.

**Comment by daavoo** [comment]
Closing this, please feel free to re-open if you consider that it has not been properly answered.

**Comment by laoreja** [comment]
Thank you very much!
