### ISSUE TITLE
ValueError: field 'n_points' occurs more than once

### ISSUE THREAD

**Issue by kmader** [daavoo/pyntcloud#196]
When I try to read some ply files generated by Constructor for Project Tango, they seem to run into issues (https://www.kaggle.com/4quant/depth-generation-lightfield-imaging#20180706181348.zip). The problem looks like it is being created by numpy as other libraries mention it (https://github.com/astropy/astropy/issues/7369). Any idea where this comes from or how to get around it?

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-bd5928208b33> in <module>()
      1 from pyntcloud import PyntCloud
----> 2 PyntCloud.from_file(ply_path)

/opt/conda/lib/python3.6/site-packages/pyntcloud/core_class.py in from_file(cls, filename, **kwargs)
    128                 "Unsupported file format; supported formats are: {}".format(list(FROM)))
    129         else:
--> 130             return cls(**FROM[ext](filename, **kwargs))
    131 
    132     def to_file(self, filename, also_save=None, **kwargs):

/opt/conda/lib/python3.6/site-packages/pyntcloud/io/ply.py in read_ply(filename)
    139             data["points"] = pd.DataFrame(points_np)
    140             if mesh_size is not None:
--> 141                 mesh_np = np.fromfile(ply, dtype=dtypes["face"], count=mesh_size)
    142                 if ext != sys_byteorder:
    143                     mesh_np = mesh_np.byteswap().newbyteorder()

ValueError: field 'n_points' occurs more than once
```

**Comment by kmader** [comment]
A temporary workaround seems to be disabling reading the mesh for the ply files, but probably there is a better solution

**Comment by daavoo** [comment]
Thanks for reporting and sharing the data that causes the problem (cool point clouds BTW :)). Looking into this.

**Comment by daavoo** [comment]
After I quick test, I managed to load the ply with no problems using some internal c++ code and then save it as ASCII. 

After examiningt the c++ code and the ASCII file, it looks like I never added support in pyntcloud for PLY files with texture (like the one you linked) and because of that the parsing of the plain text header is not working as intended.

Looking into how hard would it be to add support for this PLY with texture files.

**Comment by daavoo** [comment]
Ok, I managed to add support for loading PLY with textures 💃 #197 , BUT the mapping of the UV texture coordinates to per-vertx RGB colors is still missing.

@kmader Getting the per vertex RGB colors is something that you needed or it's enought for now that the loader does not break with that kind of ply files?

Pd. I don't have a PLY file with textures of my own, would you be willing to contribute the PLY file that you shared (or other if you have) and allow me to include it in the repository in tests/data??. I would only use it for the tests but making I don't want to make it publicly available in github without your consent.
