### ISSUE TITLE
Unable to plot point cloud only meshes

### ISSUE THREAD

**Issue by GMNetto** [daavoo/pyntcloud#210]
Hi,

I am following the example [scalar_fields] normals on windows with jupyter. I am able to see the plot for

```anky.plot(mesh=True, backend="threejs")```

However, for ```anky.plot```, I get 

```
Renderer(camera=PerspectiveCamera(aspect=1.6, fov=90.0, position=(0.015119519084692001, 2.41709041595459, 7.66…

HBox(children=(Label(value='Point size:'), FloatSlider(value=0.36411228179931643, max=3.641122817993164, step=…
```

I assume the plot is not being displayed, even though it was created.

**Comment by asbe** [comment]
Hi, I observe the same when running jupyter and/or jupyterlab on a remote server. Meshes are ok - but there is no surface displayed for plotting pointclouds. I have ensured that pythreejs is installed as an extension. Any progress on this bug?

**Comment by Mitko88** [comment]
Thank you asbe! 

Considering the link I also needed to do this:

`jupyter lab clean` 
`jupyter lab build`

**Comment by daavoo** [comment]
Thanks @GMNetto for reporting andThanks @asbe and @Mitko88 for helping with this! Closing this @GMNetto feel free to reopen if the issue persists
