### ISSUE TITLE
Is there any detailed documentation or tutorials about this library?

### ISSUE THREAD

**Issue by yangj257** [daavoo/pyntcloud#211]
I found a simple documentation or tutorial  about this library on the web page(http://pyntcloud.readthedocs.io/en/latest/index.html)
, but in the documentation, there is no sample code for many modules, just only source code. Could you please provide some sample code of the modules(like octree,voxelgrid,plot,etc) just like laspy, which allows beginners to get started quickly and make your project get more attention.Thank you very much!

**Comment by daavoo** [comment]
Hola @yangj257! Thanks for the comment :)

Adding documentation for the existing modules is a very high priority for many reasons line the ones you mentioned.

In addition to the API documentation in readthedocs, you can find sample code in the form of Jupyter Notebooks in:
https://github.com/daavoo/pyntcloud/tree/master/examples

You can also try those examples without installation launching binder:
https://mybinder.org/v2/gh/daavoo/pyntcloud/master

There are a lot of things not documented yet but I'm working on having examples for all modules.

**Comment by yangj257** [comment]
First of all, I want to say that it's a great library! 
I found a lot of useful things in the examples folder which you mentioned, but I am still troubled by some problems because of the limited documents.
Could you please provide these two documents, examples/[neighbors] and examples/[sampling]?
It would be better if there were more documents,just like filter,etc!
