### ISSUE TITLE
Unsupported sampling method: mesh_random_sampling

### ISSUE THREAD

**Issue by walzimmer** [daavoo/pyntcloud#212]
The example from here does not work on binder.org:
https://github.com/daavoo/pyntcloud-notebooks/blob/master/QuickStart.ipynb

scene = PyntCloud.from_file("data/visible.ply")
sampled_points = scene.get_sample("mesh_random_sampling",n=500000,rgb=True,normals=True)
scene = PyntCloud(sampled_points)
scene.plot()

ValueError: Unsupported sampling method. Check docstring

I figured out, that changing it to this works:
sampled_points = scene.get_sample("points_random",n=5000)

**Comment by daavoo** [comment]
pyntcloud-notebooks are outdated and deprecated, please refer to https://github.com/daavoo/pyntcloud/tree/master/examples for reference notebooks.

Pd. You should change "mesh_random_sampling" to "mesh_random" in order to get the expected result.
