### ISSUE TITLE
Polyline example does not work locally

### ISSUE THREAD

**Issue by walzimmer** [daavoo/pyntcloud#213]
The Polylines example (see below) from the examples folder does not work on my computer.
The output is the following (there is not plot):
Renderer(camera=PerspectiveCamera(aspect=1.6, fov=90.0, position=(-3.051757957450718e-08, 5.046544547319412, 7…
HBox(children=(Label(value='Point size:'), FloatSlider(value=1.0109827041625976, max=10.109827041625977, step=…

I have installed it like this:
pip install git+https://github.com/daavoo/pyntcloud
python setup.py build
python setup.py install
All requirements (numpy,numba,scipy,pandas, nodejs, npm) are also installed.

`import numpy as np
import pandas as pd
from pyntcloud import PyntCloud

positions = np.random.rand(1000, 3) * 10
positions -= positions.mean(0)

points = pd.DataFrame(positions.astype(np.float32), columns=['x', 'y', 'z'])

points["red"] = (np.random.rand(1000) * 255).astype(np.uint8)
points["green"] = (np.random.rand(1000) * 255).astype(np.uint8)
points["blue"] = (np.random.rand(1000) * 255).astype(np.uint8)

cloud = PyntCloud(points)
lines = [
    {
        "color": "red",
        "vertices": [[0, 0, 0], [10, 0, 0]]
    },
    {
        "color": "green",
        "vertices": [[0, 0, 0], [0, 10, 0]]
    },
    {
        "color": "blue",
        "vertices": [[0, 0, 0], [0, 0, 10]]
    }
]
cloud.plot(polylines=lines)`

The code works only on binder.org but not locally. Any ideas?

**Comment by daavoo** [comment]
Looks similar to #210 . Looking into this

**Comment by daavoo** [comment]
@walzimmer Could you please try the answers in #210 ? Feel free to reopen if the issue persists
