### ISSUE TITLE
Point cloud from mesh with textures

### ISSUE THREAD

**Issue by dmercel** [daavoo/pyntcloud#217]
I'm not sure if it is currently possible, but I can't seem to get meshes with textures to be able to convert to pointclouds with colour.  

I've tried importing the mesh via the ply and obj routes, but neither have worked.  Pointcloud generates from the geometry but any textures are ignored.  
Is using textures possible currently?  If not it would be a great feature to add.

Thanks,

**Comment by daavoo** [comment]
Hola!

As mentioned in #196 , support for loading ply texture coordinates has been added in #197 BUT the UV->RGB color mapping for each vertez has not being implemented yet.

Your PyntCloud should have `v1_u` fields repredenting the uv coordinates for each vertex and you could try to load the texture image and implement the mapping. 

I will try to add support for loading color information from textures soon. 

Contributions for the UV->RGB conversion are wellcome.

**Comment by banesullivan** [comment]
Perhaps #248 could help here? [PyVista handles textures](https://docs.pyvista.org/examples/02-plot/plot-texture.html#sphx-glr-examples-02-plot-plot-texture-py) and [this is another example](https://github.com/pyvista/pyvista-support/issues/14#issuecomment-501777813)
