### ISSUE TITLE
Wrong example in README.md `unexpected keyword argument 'voxelgrid'`

### ISSUE THREAD

**Issue by mjgalindo** [daavoo/pyntcloud#228]
The example in the readme file gives a

```TypeError: __init__() got an unexpected keyword argument 'voxelgrid'```

Looking in the code I found `voxelgrid` should be `voxelgrid_id`

Should be an easy fix, but I'd say it's important to have a usable example in the frontpage of the project.

**Comment by daavoo** [comment]
Hola @mjgalindo ! 
You are totally right about both the bug and the importance of the frontpage examples :)

It should be fixed now, thanks!
