### ISSUE TITLE
Unable to install pyntcloud, invalid syntax error

### ISSUE THREAD

**Issue by garynobles** [daavoo/pyntcloud#229]
This is what I get when I try to pip install via git. Is this solvable?

pip install git+https://github.com/daavoo/pyntcloud.git
Collecting git+https://github.com/daavoo/pyntcloud.git
  Cloning https://github.com/daavoo/pyntcloud.git to /tmp/pip-rNP__p-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-rNP__p-build/setup.py", line 1, in <module>
        import pyntcloud
      File "pyntcloud/__init__.py", line 1, in <module>
        from .core_class import PyntCloud
      File "pyntcloud/core_class.py", line 349
        structure = ALL_STRUCTURES[name](**info, **kwargs)
                                               ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-rNP__p-build/

**Comment by daavoo** [comment]
Hola! Could you share more information about the enviroment where you are encountering the problem (O.S, Python version, Python distribution, if any, ...)??

**Comment by garynobles** [comment]
Ah using Python 2.7.15rc1, I though I was using Python3, I'll test it on python3 tomorrow, is this where the issues lies or should it be able to run on python 2.7?
OS= Ubuntu, no virtual environment.

**Comment by daavoo** [comment]
Yep, It looks like Python2 was the issue. Please feel free to re-open if you encounter other problems with Python3 :)

**Comment by yanx27** [comment]
hello, when I install pyntcloud, I face with:

Command "python setup.py egg_info" failed with error code -11 in /tmp/pip-req-build-_g7gj_4o/

**Comment by yanx27** [comment]
@daavoo
