### ISSUE TITLE
Bug found in "pyntcloud.io.read_obj()" function

### ISSUE THREAD

**Issue by weders** [daavoo/pyntcloud#230]
**Description**

If one tries to load an .obj file using the library, the following error occurs:

**TypeError: Could not operate 1 with block values unsupported operand type(s) for -: 'str' and 'int'**

This happens because the code does not correctly handle missing texture vertex coordinates in the .obj file. If there are no texture vertex coordinates, None is written to the pd.DataFrame and you cannot subtract 1 from NoneType while correcting the indices.

**Comment by thomas-frieling** [comment]
The error can be reproduced with a simple cube example from https://de.wikipedia.org/wiki/Wavefront_OBJ

File attached: [cube.obj.zip](https://github.com/daavoo/pyntcloud/files/2906533/cube.obj.zip)

**Comment by daavoo** [comment]
Fixed un #253
