### ISSUE TITLE
Can I save a pointcloud as double precision 

### ISSUE THREAD

**Issue by yaseryacoob** [daavoo/pyntcloud#234]
**Is your feature request related to a problem? Please describe.**
Need to save a cloud as double instead of single (in ascii), not clear how to do it, doesn't seem part of the library?

**Comment by Nicholas-Mitchell** [comment]
You could access the underlying points from the `xyz` attribute of a PyntCloud object, which is a numpy array - then convert it to type `np.float64` and save it to disk.
Converting from float32 to float64 isn't actually going to give you any extra precision (how would numpy know what the actual extra decimal points should be?)

If your original data is in double precision, I would suggest just feeding a copy into PyntCloud, as to not lose that original precision
