### ISSUE TITLE
PTS files are not read

### ISSUE THREAD

**Issue by markummitchell** [daavoo/pyntcloud#241]
Hello, Thanks for the great software.

I get "ValueError Points must have x,y and z coordinates" errors when I read pts files. An example is:
9
1.786 -0.154 8.507 0 117 130 149
0.683 -0.742 8.596 0 130 137 153
1.566 -0.269 8.522 11 126 135 150
1.167 -0.462 8.561 1 127 135 156
0.568 -0.775 8.613 62 132 135 152
1.171 -0.458 8.571 0 125 136 156
0.801 -0.652 8.591 58 134 141 160
0.615 -0.781 8.63 0 135 140 159
2.027 -0.036 8.489 0 121 132 152

OS: Windows and Linux
Version: current

**Comment by daavoo** [comment]
Could you share the code that is causing this??

Could you share the file or clarify if the first row with a single '9' is included in the file??

**Comment by markummitchell** [comment]
The first line of the file is '9', and the last line is '2.027 -0.036 8.489 0 121 132 152'. I verified that after copying and pasting the pts file above into a file, the file will be correctly read by Autodesk ReCap.

The ValueError exception comes from core_class.py:
 def points(self, df):
        if not isinstance(df, pd.DataFrame):
            raise TypeError("Points argument must be a DataFrame")
        elif not set(['x', 'y', 'z']).issubset(df.columns):
            raise ValueError("Points must have x, y and z coordinates")

**Comment by ScarlettLeong** [comment]
you should read the i/o page [https://pyntcloud.readthedocs.io/en/latest/io.html](https://pyntcloud.readthedocs.io/en/latest/io.html)
Internally, PyntCloud.from_file is just calling the pandas function .read_csv when you give it a valid ascii format.

So check the linked documentation to explore all the possible arguments in order to adjust them to read your ascii file.

**Comment by markummitchell** [comment]
Sorry. I realize there are spaces causing the problem. Thanks

**Comment by daavoo** [comment]
Thanks @ScarlettLeong :)
