### ISSUE TITLE
Add "linewidth" as a parameter to polylines in plot method

### ISSUE THREAD

**Issue by Nicholas-Mitchell** [daavoo/pyntcloud#244]
I would like to change the thickness of the polylines, based on some variable. This helps encode extra information into the plots (e.g. thicker lines could mean greater uncertainty on a prediction.

I have added a solution, which simply taps into the ability that `pythreejs` already implements. It only requires a minimal change in the following function, found in `pyntcloud/plot/pythreejs_backend.py`:

```python
def get_polylines_pythreejs(polylines):
    lines = []
    for x in polylines:
        line_geometry = pythreejs.Geometry(
            vertices=x["vertices"])
        _width = x.get("linewidth", 1.0)    # add this line to look for linewidth param, or return default (1.0) if not given
        line = pythreejs.Line(
            geometry=line_geometry,
            material=pythreejs.LineBasicMaterial(color=x["color"], linewidth=_width),    # pass it here
            type='LinePieces')
        lines.append(line)

    return lines

```
That's it!  Because the way it is written, I am not sure you would even need to add a test for it.

I don't have time right now to create a PR, but wanted to leave this here in case @daavoo manages to get it done. Otherwise as a reminder for me on how to hack it, when I need it next time  :)

**Describe alternatives you've considered**
I don't think there are any sensible alternatives.

**Comment by daavoo** [comment]
Thanks @Nicholas-Mitchell . I added the suggested changes
