### ISSUE TITLE
Interoperability with PyVista

### ISSUE THREAD

**Issue by banesullivan** [daavoo/pyntcloud#247]
Would it be of interest here to use [PyVista](https://github.com/pyvista/pyvista) as a supporting module for 3D visualization?

It should be pretty straightforward as a `PyntCloud` is basically the same as a  `pyvista.PolyData` object (`vtkPolyData`). Also, voxel grids/meshes could easily be represented by `pvvista.StructuredGrid`, `pyvista.UnstructruedGrid`, or `pyvista.UnifromGrid`.

What do you all think of having way a to go back and forth between the `PyntCloud` class and `pyvista`'s `PolyData` class? This would allow you all to leverage all of PyVista's filtering algorthims [for general datasets](https://docs.pyvista.org/tools/filters.html) and [for point based datasets](https://docs.pyvista.org/types/points.html#pyvista-polydata-grid-class-methods)

And plotting a point cloud using PyVista is simply:

```py
import numpy as np
import pyvista as pv

points = np.random.rand(1000, 3)

pc = pv.PolyData(points)

pc.plot(point_size=5, show_grid=True, color='red')
```

![download](https://user-images.githubusercontent.com/22067021/59555904-67640880-8f77-11e9-9446-440bb07a074d.png)

**Comment by banesullivan** [comment]
And we have useful features like Eye Dome Lighting for improved depth perception. See [this example](https://docs.pyvista.org/examples/02-plot/plot-edl.html):

```py
import pyvista as pv
from pyvista import examples

# Eye dome lighting is not currently supported by VTKjs
pv.rcParams['use_panel'] = False

point_cloud = examples.download_lidar()

# Plot a typical point cloud with no EDL
p = pv.Plotter()
p.add_mesh(point_cloud, color='tan', point_size=5)
p.show()
```

![sphx_glr_plot-edl_003](https://user-images.githubusercontent.com/22067021/59555928-da6d7f00-8f77-11e9-900c-c1495e995b5e.png)


```py
# Plot with EDL
p = pv.Plotter()
p.add_mesh(point_cloud, color='tan', point_size=5)
p.enable_eye_dome_lighting()
p.show()
```

![sphx_glr_plot-edl_004](https://user-images.githubusercontent.com/22067021/59555926-d80b2500-8f77-11e9-8505-b23207ffe737.png)

**Comment by daavoo** [comment]
Hola @banesullivan !

First of all: WoW! :open_mouth: PyVista looks awesome, great work!

So yes, It would definetly be quite cool to add support for PyVista as plotting backend and to include some sort of conversor from/to PyVista's Polydata. 

I would certainly work on this myself but contributions and/or ideas are always wellcome.

**Comment by banesullivan** [comment]
Thanks, @daavoo! I'm glad to see you think PyVista would fit well here as a supporting module for 3D viz!

I'll try to make time to play around here and see if I can get a PR going
