### ISSUE TITLE
Plot gets stuck "Loading widget..."

### ISSUE THREAD

**Issue by gabegrand** [daavoo/pyntcloud#251]
I can't get the example plot to display inside Jupter notebook with "threejs" (same issue as #177). I switched to "pythreejs" backend, and the widget gets stuck loading.

Running JupyterLab v1.0.0 with Python 3.6 on Linux Ubuntu 16.04

![Screen Shot 2019-07-03 at 2 59 11 PM](https://user-images.githubusercontent.com/10052880/60618070-2e16ff80-9da3-11e9-91dc-3725f1e5d17c.png)

**Comment by daavoo** [comment]
Hola @gabegrand ! Thanks for pointing the but out.

It looks like it might be something more related to jupyterlab&pythreejs integration than pyntcloud itself.

I found this issue:

https://github.com/jupyter-widgets/pythreejs/issues/268

Which seems (from a quick view) related.

Please let me know if you find a solution :)
