### ISSUE TITLE
Attribute Issue in PCD file

### ISSUE THREAD

**Issue by Dinatorehanova** [daavoo/pyntcloud#257]
Hi,
I am directly using the bag file to feed in the pcl_ros library using the command rosrun pcl_ros bag_to_pcd <input_file.bag> <output_directory>

As topic, I am using the /os1_cloud_node/points.

I have shared one of my bag file and a pcd file generated from this bag here.It would be very helpful if you could kindly have a look and guide me what corrections do we have to do to get all the fields in the pcd file attribute.

bag- https://drive.google.com/file/d/1a07ZoVyITabAu39hr9EVeHMpWqmCRVSd/view?usp=sharing

pcd- https://drive.google.com/file/d/1ZI9hUIjoYdnPh_crXvKg-fJcRqrTSzXJ/view?usp=sharing

The head command is giving the following output for the pcd 
![image](https://user-images.githubusercontent.com/51459647/63633202-7fa07580-c601-11e9-8716-174876d052b9.png)

When I am converting my the point cloud into the pcd file using the pcl_ros library then I am getting a constant value of 0 under the the noise,time, ring, reflectivity, range column. And also in terms of the x,y,z many points has a value of 0.

Field attribute of my pcd file 

![image](https://user-images.githubusercontent.com/51459647/63633205-a2328e80-c601-11e9-8220-0e19e0e1b9b5.png)

**Comment by daavoo** [comment]
Hola @Dinatorehanova ! I'm not sure but I think that the issue you are reporting it's not related to this repo but rather would be better reported in:
https://github.com/ros-perception/perception_pcl/issues
