### ISSUE TITLE
plot 3D voxelgrid error

### ISSUE THREAD

**Issue by sunnyHelen** [daavoo/pyntcloud#259]
**Describe the bug**
when I try to plot 3D voxelgrid, I get a .html file. But it turns out nothing like this
![image](https://user-images.githubusercontent.com/28101548/64093556-29b79480-cd9c-11e9-9592-86ef32fa527a.png)
I use class VoxelGrid(Structure) to build my voxel, and I can get the 2D plot. 
**To Reproduce**

**Expected behavior**
I want to visualize my voxel like the examples you show in VoxelGrid.ipynb
**Screenshots**
![image](https://user-images.githubusercontent.com/28101548/64093556-29b79480-cd9c-11e9-9592-86ef32fa527a.png)
**Desktop (please complete the following information):**
 - Browser (if necessary) [e.g. chrome, safari] chrome
 - Version (master branch commit) 75.0.3770.100

**Additional context**

**Comment by sunnyHelen** [comment]
Oh, sorry. I found the solution.

**Comment by daavoo** [comment]
Hola @sunnyHelen ! Glad to hear that you managed to found the solution. Could you share what was the problem/solution in order to serve as reference for other people?
