### ISSUE TITLE
Update Installation Docs

### ISSUE THREAD

**Issue by daavoo** [daavoo/pyntcloud#265]
**Is your feature request related to a problem? Please describe.**
The installation instructions in https://pyntcloud.readthedocs.io/en/latest/ are outdated.

**Describe the solution you'd like**
Update the installation instructions with the new conda-forge and pypi options

**Comment by Pachwenko** [comment]
I'll update the docs, but if the verbiage is off feel free to say something!

Also, I think requirements.txt is incorrect so we may want to remove that.
