### ISSUE TITLE
Header / comments Editing

### ISSUE THREAD

**Issue by cell-a** [daavoo/pyntcloud#272]
Hello  @daavoo 
i need to edit existing ply file contain header (text) & binary without effecting the binary
i want to replace in comments or in the header 
i'm tried to use edit_ply from this code 
[Read & Write Ply File](https://github.com/daavoo/pyntcloud/blob/master/pyntcloud/io/ply.py)
but its didn't work 
i have paths in the comments 
and i need to edit this paths 
also i'm tried to use normal code (re , str.replace) but its make error in encoding 
please support

**Comment by daavoo** [comment]
Hola @cell-a I think that you can now do what you needed installing pyntcloud from the current `master` branch:

```python
