### ISSUE TITLE
scalar field writing

### ISSUE THREAD

**Issue by Ciaran1981** [daavoo/pyntcloud#281]
Is it possible to write a custom scalar field? Can the data be inserted via numpy array?

**Comment by tgoelles** [comment]
Yes that would also be interesting for lidar application. Lidar give x,y,z data and in addition intensity, noise, range and more.

**Comment by Ciaran1981** [comment]
Yes - it can be done outside this lib but would be great given it's other utilities

**Comment by daavoo** [comment]
Hola @Ciaran1981!

The [pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) stored at `Pyntcloud.points` can be modified as you wish. A new `scalar_field` can be considered in this case a new column of this pandas DataFrame so you can just add the column as follows:

```python
from pyntcloud import PyntCloud

cloud = PyntCloud.from_file("test/data/filters/filters.ply")
# compute a new scalar_field
# you can retrieve the new scalar field from whatever source you need
above_03 = cloud.points["z"] > 0.3
# add the new scalar field
cloud.points["my_new_scalar_field"] = above_03
```

**Comment by Ciaran1981** [comment]
Ah yes I discovered this after I asked the question and forgot to update. Thanks for clarifying. Great lib!
