### ISSUE TITLE
could you help out converting it to .obj, please?

### ISSUE THREAD

**Issue by AndreV84** [daavoo/pyntcloud#293]
https://storage.googleapis.com/nvidia-dev/113620.ply
At my end I either get the points lost or the color lost with conversion
`[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyntcloud import PyntCloud
>>> diamond = PyntCloud.from_file("cloud.ply")
>>> convex_hull_id = diamond.add_structure("convex_hull")
>>> convex_hull = diamond.structures[convex_hull_id]
>>> diamond.to_file("diamond_hull.obj", also_save=["mesh"])`

**Comment by AndreV84** [comment]
https://github.com/IntelRealSense/librealsense/issues/7800#issuecomment-729831606

**Comment by daavoo** [comment]
Hola @AndreV84 , I'm afraid that pyntcloud does not currently supports reading/writing to/from `.obj` files with per-vertex color information. 

As far as I remember when adding the `.obj` code, vertex coloring is not considered part of the format "standard" and it is only supported by a few applications (i.e. Meshlab).

Looking at how it appears to be implemented in Meshlab (https://gamedev.stackexchange.com/a/66270) it might be feasible to add support to vertex coloring for the `.obj` format in pyntcloud with minor modifications, will change the label to Feature Request. Contributions are allways wellcome.

**Comment by daavoo** [comment]
I was feeling hacky so I think that you could use the following:

```

**Comment by AndreV84** [comment]
Thank you very much!
It seems I was able to export ply to obj with meshlab.
I can visualize the obj in meshlab.
Not sure if it wil get drawn in other visualizers though.

Could you elaborate on how to visualize from terminal with the python tool? I never got any window to pop up

**Comment by daavoo** [comment]
> Thank you very much!
> It seems I was able to export ply to obj with meshlab.
> I can visualize the obj in meshlab.
> Not sure if it wil get drawn in other visualizers though.
> 
> Could you elaborate on how to visualize from terminal with the python tool? I never got any window to pop up

If you want to visualize directly from the terminal, you need to first install matplotlib (`pip install matplotlib`). And then:

**Comment by AndreV84** [comment]
Thank you very much!
