### ISSUE TITLE
Argument to know which point goes in which voxel

### ISSUE THREAD

**Issue by mserouar** [daavoo/pyntcloud#298]
Hello,

I don't know if it exists yet, but why not extracting in a file the xyz position of each points and their linked voxel. 
To know which points contain a voxel. Maybe in add_structure.

Congrats

**Comment by daavoo** [comment]
There is already a `scalar_field` that contains that information. You would need to first add a voxelgrid:
```

**Comment by daavoo** [comment]
Feel free to re-open if you consider that the question has not been properly answered

**Comment by mserouar** [comment]
Just a quick thing, actually I'm more interested in linking voxels centers coordinates (in grids) with voxel class and then join with original point cloud. Is there a way to do it ?
