### ISSUE TITLE
KeyError: 'curvature(K(16))'

### ISSUE THREAD

**Issue by kidpaul94** [daavoo/pyntcloud#306]
**Describe the bug**
I was trying to exactly replicate the code here on stackoverflow:
https://stackoverflow.com/questions/42476839/is-gaussian-mean-curvatures-applicable-for-rough-surfaces/42489903?noredirect=1#comment72136158_42489903

And the following command gives an error:
curvature = cloud.points["curvature(K(16))"]
raise KeyError(key) from err
KeyError: 'curvature(K(16))'

**Expected behavior**
I was trying to get edges from the original pointclouds as shown in the stackoverflow post. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: pyntcloud 0.1.4

**Additional context**
I couldn't find any documentation regarding this "curvature(K(16))" in cloud.points and do the task I want to do. I wonder whether this is under modification since the comment on stackoverflow was posted in 2017.

**Comment by kidpaul94** [comment]
Never mind, I figured out.

**Comment by daavoo** [comment]
Hola @kidpaul94 , what was the fix?? Using `"curvature(K(10))"¿

**Comment by kidpaul94** [comment]
cloud.add_scalar_field("curvature", ev=ev) gave me curvature(11), so I used that.
