### ISSUE TITLE
I have not been able to apply the SOR filter. 

### ISSUE THREAD

**Issue by MHSiebers** [daavoo/pyntcloud#340]
I am running pyntcloud 0.3.1 and have not been able to get the SOR filter to work. I had it running previously and am wondering if a scipy update or other update affected the kdtree or SOR. 

I am still able to produce a point cloud but it appears unfiltered. Changing the z_max value has no effect.

**Comment by daavoo** [comment]
Hola @MHSiebers ! Sorry for late response, was the issue resolved? If not, could you share more details by sharing the code causing the error and/or the traceback?
