### ISSUE TITLE
Have a bug when using with spicy1.9.0

### ISSUE THREAD

**Issue by trinhnhut-gif** [daavoo/pyntcloud#341]
Hello,
when I was using spicy1.9.0, pyntcloud had a bug like the one below. Could you give me some suggestions? Thank you
![image](https://user-images.githubusercontent.com/85855232/195022362-1c57dd00-850e-4c04-933c-70e5d984295b.png)

**Comment by trinhnhut-gif** [comment]
I have a solution, find k_neighbors.py in pyntcloud and change **n_jobs** to **workers**

**Comment by daavoo** [comment]
@trinhnhut-gif Which `pyntcloud` version are you using? It should work in latest version

**Comment by trinhnhut-gif** [comment]
I have installed the newest version and it worked successfully. Thank you so much
