### ISSUE TITLE
Error on call of function plot

### ISSUE THREAD

**Issue by cercao** [daavoo/pyntcloud#52]
Hi!

I`m trying to run the first code in readme. Probably I`m doing something wrong.. Could you help ?

I`m using a MacBook pro. I`ve installed everything with miniconda (some packages I needed to install globally because miniconda does not have support for some packages to OSx64).

Then a ran in jupyter a test.py with the commands in readme. Also, I`ve downloaded a .ply sample.
The command print(scene) works fine, but when I call the .plot(), an error happens: 

Traceback (most recent call last):
  File "test1.py", line 8, in <module>
    scene.plot()
  File "/Users/lrodrigues/miniconda2/envs/pyntcloud/lib/python3.6/site-packages/pyntcloud/core_class.py", line 604, in plot
    return plot_PyntCloud(new_PyntCloud, output_name=output_name)
  File "/Users/lrodrigues/miniconda2/envs/pyntcloud/lib/python3.6/site-packages/pyntcloud/plot/points.py", line 17, in plot_PyntClou
d
    with open(src, "r") as inp, open(dst, "w") as out:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lrodrigues/miniconda2/envs/pyntcloud/lib/python3.6/site-packages/pyn
tcloud/plot/points.html'

Do you have any tip to solve this ?

Thanks!

**Comment by daavoo** [comment]
Thanks for reporting!

Let me look into this.

Regarding conda packages on Mac OS, I'm working on loading all dependencies to conda-forge, a comunnity-driven alternative to anaconda's default channel.

**Comment by daavoo** [comment]
Found the problem. You were not doing something wrong. I forgot to add data filles (with no .py extensions) in setup.py, so the points.html file is missing. I'll fix this soon.

Pd. I'm insteresting in knowing wich packages failed to install using the pyntcloud_env.yml file, could you pass me a list??

**Comment by daavoo** [comment]
@cercao Please could you confirm that this is fixed on Mac Os??
